<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<AssemblyName>IconBrowser</AssemblyName>
		<RootNamespace>IconBrowser</RootNamespace>

	</PropertyGroup>

	<ItemGroup>

		<PackageReference Include="MahApps.Metro.IconPacks"
						  Version="*" />

	</ItemGroup>

</Project>